
scheduler: # Scheduler options
  restarting: 'relaunch'

parameters: # Session parameters
  env: 'dev'

tasks: # Meta tasks
  - class: PyLoader
    path: 'tasks/'
    on_startup: True
    glob: '**/tasks.py'

logging: # Logging settings
  version: 1
  handlers: # One readable handler is required
    mem_task:
      (): "redengine.log.MemoryHandler"
  loggers:
    redengine.task:
       handlers: [
         'mem_task' # redengine.task must have readable logger
       ]
       level: 'INFO'
       propagate: False