
scheduler:
  # Scheduler options
  restarting: 'relaunch'

parameters:
  # Add your parameters here that are passed to
  # tasks on request
  env: 'dev'

tasks:
  # Put your meta tasks here
  - class: TaskLoader
    path: 'tasks/'
    glob: '**/tasks.yaml'
    on_startup: True
  - class: ExtensionLoader
    path: 'tasks/'
    on_startup: True
  - class: PyLoader
    path: 'tasks/'
    glob: '**/tasks.py'
    on_startup: True

logging:
  clear_existing: True
  version: 1
  disable_existing_loggers: True

  formatters:
    standard:
      format: '%(asctime)s %(levelname)s %(message)s'

    csv_task_formatter:
      (): redengine.log.CsvFormatter
      fields: [
        task_name,
        asctime,
        action,
        start, # Start of the task
        end, # End of the task ('run' does not have end)
        runtime,
        message
      ]
    dict_task_formatter:
      (): redengine.log.AttributeFormatter
      include: ['created', 'task_name', 'action', 'exc_text', 'start', 'end', 'runtime']

  handlers:
    default:
      level: 'DEBUG'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    stderr:
      level: 'ERROR'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'

    # Task handlers, choose one for the redengine.task logger
    csv_task:
      (): "redengine.log.CsvHandler"
      formatter: "csv_task_formatter"
      filename: "tasks.csv"
      make_dir: True
      delay: True
    mem_task:
      (): "redengine.log.MemoryHandler"
    mongo_task:
      (): "redengine.log.MongoHandler"
      # If you wish to get the connection
      # string from elsewhere than from
      # this config file, you can just set
      # a dummy here and reset it after
      # parsing this file.
      formatter: "dict_task_formatter"
      client: 'mongodb://localhost:27020'
      database: 'redengine'
      collection: 'task_log'

  loggers:
    '': # root logger
       handlers: ['default']
       level: 'WARNING'
       propagate: False
    redengine.task:
       handlers: [
       'default',

       # Change this to preferred.
        # 'mem_task', 
        'csv_task',
        # 'mongo_task',
       ]
       level: 'INFO'
       propagate: False
    redengine.scheduler:
       handlers: ['default']
       level: 'INFO'
       propagate: False
    __main__:
       handlers: ['default']
       level: 'DEBUG'
       propagate: False