# Clear existing tasks & schedulers
clear_existing: True

# Loggers, handlers, formatters
logging:
  version: 1
  disable_existing_loggers: True

  formatters:
    standard:
      format: '%(message)s'
    # Custom
    rec_formatter:
      (): powerbase.log.AttributeFormatter

  handlers:
    default:
       level: 'INFO'
       formatter: 'standard'
       class: 'logging.StreamHandler'
       stream: 'ext://sys.stdout' # Default is stderr
    stdout:
       level: 'INFO'
       formatter: 'standard'
       class: 'logging.StreamHandler'
       stream: 'ext://sys.stdout'  # Default is stderr
    stderr:
       level: 'ERROR'
       formatter: 'standard'
       class: 'logging.StreamHandler'
       stream: 'ext://sys.stdout'  # Default is stderr

    # Custom
    mem_scheduler:
       (): "powerbase.log.MemoryHandler"
       store_as: "dict"
       formatter: 'rec_formatter'
    mem_task:
       (): "powerbase.log.MemoryHandler"
       store_as: "dict"
       formatter: 'rec_formatter'
    mem_task_maintain:
       (): "powerbase.log.MemoryHandler"
       store_as: "dict"
       formatter: 'rec_formatter'

  loggers:
    '': # root logger
       handlers: ['default']
       level: 'WARNING'
       propagate: False
    powerbase.task: 
       handlers: ['stderr', 'mem_task']
       level: 'INFO'
       propagate: False
    powerbase.task._process:
      # Preventing the logger of a 
      # process task to use parent
      # logger
      propagate: False
    powerbase.task.maintainer: 
       handlers: ['mem_task_maintain']
       level: 'INFO'
       propagate: False
    powerbase.scheduler:
       handlers: ['mem_scheduler']
       level: 'INFO'
       propagate: False
    __main__:  # if __name__ == '__main__'
       handlers: ['default']
       level: 'DEBUG'
       propagate: False