# Simple Memory logger that also
# logs to std out
clear_existing: True

# Loggers, handlers, formatters
logging:
  version: 1
  disable_existing_loggers: True

  formatters:
    standard:
      format: '%(message)s'
    # Custom
    rec_formatter:
      (): redengine.log.AttributeFormatter

  handlers:
    default:
       level: 'INFO'
       formatter: 'standard'
       class: 'logging.StreamHandler'
       stream: 'ext://sys.stdout' # Default is stderr

    # Custom
    mem_scheduler:
       (): "redengine.log.MemoryHandler"
       store_as: "dict"
       formatter: 'rec_formatter'
    mem_task:
       (): "redengine.log.MemoryHandler"
       store_as: "dict"
       formatter: 'rec_formatter'

  loggers:
    '': # root logger
       handlers: ['default']
       level: 'WARNING'
       propagate: False
    redengine.task: 
       handlers: ['mem_task', 'default']
       level: 'INFO'
       propagate: False
    redengine.task._process:
      # Preventing the logger of a 
      # process task to use parent
      # logger
      propagate: False
    redengine.scheduler:
       handlers: ['mem_scheduler', 'default']
       level: 'INFO'
       propagate: False
    __main__:  # if __name__ == '__main__'
       handlers: ['default']
       level: 'DEBUG'
       propagate: False