# YAMLLoader also supports listing multiple tasks in one YAML file
- class: ScriptTask
  name: 'mytask-2'
  path: 'example.py'
  func: 'example_func'
  execution: 'process'
  start_cond: 'daily between 08:00 and 14:00 | daily between 16:00 and 22:00' 
  parameters:
    myname: 'Ahti'

- class: ScriptTask 
  name: 'mytask-3'
  path: 'example.py'
  func: 'example_func'
  execution: 'process'
  start_cond: 'daily between 08:00 and 14:00 | daily between 16:00 and 22:00' 
  parameters:
    myname: 'Tapio'