# This is a task setup read by YAMLLoader. This file can be anywhere in this directory
class: ScriptTask # Name of the task class. See powerbase.tasks.CLS_TASKS

# Name of this task. Each task should have unique name.
name: 'mytask-1'

# What the ScriptTask will execute
path: 'example.py'
func: 'example_func'

# Define how the task is executed, allowed: 'main', 'thread', 'process'
execution: 'process'
# Define when the task starts.
start_cond: 'daily between 08:00 and 14:00 | daily between 16:00 and 22:00' 

# Additional parametrization for only this task
parameters:
  myname: 'Ukko'