
# You can also load tasks from YAML
# configuration files such as this
# one.

# The file can be structured as this
# (dict of dicts) or as list of dict.
# In this example the key of the first
# dictionary is the name of the tasks
# and the inner dictionaries are the
# configurations of each tasks. These
# configurations are passed to the 
# classes specified in 'class' key.

# For some classes (like FuncTask)
# the 'class' does not need to be 
# specified if a 'path' key is set
# and it's a Python file.

# If list of dicts are used, the 'name' 
# key should be specified in each task
# unless default naming is used. 

my-yaml-task-1:
  path: 'funcs.py'
  func: 'main'
  start_cond: 'minutely'
  execution: 'main'
  parameters: 
    my_task_param: 'my value' # Function parameter
    
my-yaml-task-2:
  path: 'funcs.py'
  func: 'do_things' # Runs on another process
  execution: 'thread'
